name: Teste de Runner Self-Hosted

on: workflow_dispatch

jobs:
  test-runner:
    runs-on: "test-runner-scale-set"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Executar teste
        run: |
          echo "Hello World"
      - run: date
      - run: sleep 2
      - run: date
